### ISSUE TITLE
ClojureScript/Lumo port

### ISSUE THREAD

**Issue by arichiardi** [mixradio/faraday-atom#1]
Hi there,
I have come across this library and it really fits into one my use cases, where I could use it from an AWS lamdba function in order to keep state within an atom.

I was wondering if there is any plan in porting the library to ClojureScript and/or Lumo in the near future.

I could of course take care of this, given some time. Just wanted to open the discussion here. The code looks pretty simple and it might be just a matter of adding a bunch of reader conditionals (I am so thankful no macros have been used here).

Nice nice project anyways.

Thank you!

**Comment by wotbrew** [comment]
Hi! 

Sounds like an interesting idea! I am no longer using this lib in my place of work, but have released a very similar lib that is used in production right now but it does slightly more: https://github.com/riverford/durable-ref. This may be more suitable, its going to be more actively used and maintained, secondly it has simpler storage requirements, where as faraday-atom is very strictly tied to dynamodb & faraday (a clojure only library).

If you think it would be possible, a PR to durable-ref to add cross platform compatibility and the ability to use a js/node amazon client for dynamo would be very, very welcome! Of course totally happy to contribute to any discussion/ideas around this too. 

Thanks!

**Comment by arichiardi** [comment]
Hey Dan, the other library is super great, I will explore it a bit more but I don't know if I need all of that ...my use case is limited to DynamoDB and compare and swap for now...
If you don't maintain this like anymore, maybe I can be a collaborator? Just to make things easier for me to patch and deploy 😄

**Comment by arichiardi** [comment]
Hi @danstone I am back on this one :smile: 

I think my use case is really limited just to an atom on DynamoDB at the moment and of course given the also limited time I have it is probably better to contribute to this project. This is exactly the right level of abstraction I need :smile: 

So what do you think if I put together a patch? Alternately I can fork/clone part with attribution.

It makes sense to keep the two together though.

**Comment by wotbrew** [comment]
Hi @arichiardi 

Feel free to start with a fork if you want, I would suggest that you use a different name than 'faraday' because that is a clojure only library. This was always intended as a addon library to that one.

I would be super keen to see a clojurescript port of the core idea behind durable-ref, I think that would be awesome. I'm not sure if I'll get to it myself though.

**Comment by arichiardi** [comment]
Ok I will for sure peek at your implementation in `durable-ref` so I thank you in advance :smile:
